# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LogCataWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CatalogWindow(object):
    def setupUi(self, CatalogWindow):
        CatalogWindow.setObjectName("CatalogWindow")
        CatalogWindow.resize(1057, 738)
        self.centralwidget = QtWidgets.QWidget(CatalogWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(200, 20, 31, 651))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 110, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 110, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(340, 180, 54, 12))
        self.label_3.setObjectName("label_3")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(390, 180, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(360, 110, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(560, 110, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(340, 250, 75, 23))
        self.SearchButton.setObjectName("SearchButton")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 110, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 160, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 200, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 240, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(60, 340, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(60, 380, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(70, 310, 54, 12))
        self.label_4.setObjectName("label_4")
        CatalogWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CatalogWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1057, 23))
        self.menubar.setObjectName("menubar")
        self.menu111 = QtWidgets.QMenu(self.menubar)
        self.menu111.setObjectName("menu111")
        CatalogWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CatalogWindow)
        self.statusbar.setObjectName("statusbar")
        CatalogWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu111.menuAction())

        self.retranslateUi(CatalogWindow)
        QtCore.QMetaObject.connectSlotsByName(CatalogWindow)

    def retranslateUi(self, CatalogWindow):
        _translate = QtCore.QCoreApplication.translate
        CatalogWindow.setWindowTitle(_translate("CatalogWindow", "编目系统"))
        self.label.setText(_translate("CatalogWindow", "出发"))
        self.label_2.setText(_translate("CatalogWindow", "到达"))
        self.label_3.setText(_translate("CatalogWindow", "日期"))
        self.SearchButton.setText(_translate("CatalogWindow", "搜索"))
        self.pushButton.setText(_translate("CatalogWindow", "主页"))
        self.pushButton_2.setText(_translate("CatalogWindow", "航班搜索"))
        self.pushButton_3.setText(_translate("CatalogWindow", "我的订单"))
        self.pushButton_4.setText(_translate("CatalogWindow", "出行服务"))
        self.pushButton_6.setText(_translate("CatalogWindow", "修改资料"))
        self.pushButton_7.setText(_translate("CatalogWindow", "退出登录"))
        self.label_4.setText(_translate("CatalogWindow", "个人中心"))
        self.menu111.setTitle(_translate("CatalogWindow", "文件"))
